version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accountingko
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/accountingko
      EMAIL_SERVER_HOST: live.smtp.mailtrap.io
      EMAIL_SERVER_PORT: 2525
      EMAIL_SERVER_USER: smtp@mailtrap.io
      EMAIL_SERVER_PASSWORD: 7e5af322653c0e22eda2e8c4953f82e4
      EMAIL_FROM: hello@demomailtrap.co
      AUTH_SECRET: your-secret
    command: >
      sh -c "
      pnpm install &&
      npx prisma generate &&
      npx prisma db push &&
      pnpm run dev
      "
    volumes:
      - .:/app

volumes:
  db_data:

